"""make_name_en_optional

Revision ID: 26f67011f40b
Revises: 5c9c85700c6a
Create Date: 2026-07-06 14:22:28.259088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f67011f40b'
down_revision: Union[str, None] = '5c9c85700c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_affiliate_configs_tenant_id', table_name='affiliate_configs')
    op.create_index(op.f('ix_affiliate_configs_tenant_id'), 'affiliate_configs', ['tenant_id'], unique=False)
    op.alter_column('users', 'name_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_users_public_id', table_name='users')
    op.create_index('ix_users_public_id', 'users', ['public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_public_id', table_name='users')
    op.create_index('ix_users_public_id', 'users', ['public_id'], unique=True)
    op.alter_column('users', 'name_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_affiliate_configs_tenant_id'), table_name='affiliate_configs')
    op.create_index('ix_affiliate_configs_tenant_id', 'affiliate_configs', ['tenant_id'], unique=True)
    # ### end Alembic commands ###
