"""add_user_idempotency_key

Revision ID: 36a5b5dce829
Revises: 07832f6c4879
Create Date: 2026-07-06 13:05:34.672591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a5b5dce829'
down_revision: Union[str, None] = '07832f6c4879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_affiliate_configs_tenant_id', table_name='affiliate_configs')
    op.create_index('ix_affiliate_configs_tenant_id', 'affiliate_configs', ['tenant_id'], unique=True)
    #op.create_index('ix_cert_entity', 'quality_certificates', ['certified_entity_type', 'certified_entity_id'], unique=False)
    op.add_column('users', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.drop_index('ix_users_public_id', table_name='users')
    op.create_index('ix_users_public_id', 'users', ['public_id'], unique=False)
    op.create_index(op.f('ix_users_idempotency_key'), 'users', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_idempotency_key'), table_name='users')
    op.drop_index('ix_users_public_id', table_name='users')
    op.create_index('ix_users_public_id', 'users', ['public_id'], unique=True)
    op.drop_column('users', 'idempotency_key')
    op.drop_index('ix_cert_entity', table_name='quality_certificates')
    op.drop_index('ix_affiliate_configs_tenant_id', table_name='affiliate_configs')
    op.create_index('ix_affiliate_configs_tenant_id', 'affiliate_configs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
