"""make_name_ar_optional

Revision ID: 5c9c85700c6a
Revises: 36a5b5dce829
Create Date: 2026-07-06 14:02:06.330252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9c85700c6a'
down_revision: Union[str, None] = '36a5b5dce829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('ix_cert_entity', 'quality_certificates', ['certified_entity_type', 'certified_entity_id'], unique=False)
    op.alter_column('users', 'name_ar',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_users_public_id', table_name='users')
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.create_index('ix_users_public_id', 'users', ['public_id'], unique=False)
    op.alter_column('users', 'name_ar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    #op.drop_index('ix_cert_entity', table_name='quality_certificates')
    # ### end Alembic commands ###
