"""rename_metadata_to_invoice_metadata

Revision ID: 9e9aaf1cbbc8
Revises: daa080205fdb
Create Date: 2026-07-23 06:16:10.678728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9aaf1cbbc8'
down_revision: Union[str, None] = 'daa080205fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_affiliate_configs_tenant_id', table_name='affiliate_configs')
    op.create_index(op.f('ix_affiliate_configs_tenant_id'), 'affiliate_configs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affiliate_configs_tenant_id'), table_name='affiliate_configs')
    op.create_index('ix_affiliate_configs_tenant_id', 'affiliate_configs', ['tenant_id'], unique=True)
    # ### end Alembic commands ###
