# .ai-generated/k8s/base/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: eppne-secretstore
  namespace: eppne
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: backend-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eppne-externalsecret
  namespace: eppne
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: eppne-secretstore
    kind: SecretStore
  target:
    name: eppne-secrets
    creationPolicy: Owner
  data:
  - secretKey: SECRET_KEY
    remoteRef:
      key: eppne/prod/secrets
      property: SECRET_KEY
  - secretKey: DATABASE_URL
    remoteRef:
      key: eppne/prod/secrets
      property: DATABASE_URL
  - secretKey: REDIS_URL
    remoteRef:
      key: eppne/prod/secrets
      property: REDIS_URL
  - secretKey: S3_ENDPOINT
    remoteRef:
      key: eppne/prod/secrets
      property: S3_ENDPOINT
  - secretKey: S3_ACCESS_KEY
    remoteRef:
      key: eppne/prod/secrets
      property: S3_ACCESS_KEY
  - secretKey: S3_SECRET_KEY
    remoteRef:
      key: eppne/prod/secrets
      property: S3_SECRET_KEY