global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'eppne-api'
    static_configs:
      # ✅ تم استبدال host.docker.internal بـ Service DNS الصحيح داخل الكلستر
      - targets: ['eppne-backend-service.eppne.svc.cluster.local:80']